# Generated by Django 2.0.1 on 2018-01-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20180123_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='collection_date',
            field=models.DateField(),
        ),
    ]
