# Generated by Django 2.0.1 on 2018-01-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180123_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartfleet',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_fleet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.CartFleet'),
            preserve_default=False,
        ),
    ]
