# Generated by Django 2.0.1 on 2018-02-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20180130_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='uploads/')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.CartFleet')),
            ],
        ),
    ]
