# Generated by Django 2.0.1 on 2018-05-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2018-05-20 07:42:00', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.DataCollection'),
            preserve_default=False,
        ),
    ]
