# Generated by Django 2.0.1 on 2018-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20180520_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='name',
            field=models.CharField(default='2018-05-20 07:53:27', max_length=30),
        ),
    ]
