# Generated by Django 2.0.1 on 2018-05-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20180520_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('code', models.IntegerField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.DataSet')),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='name',
            field=models.CharField(default='2018-05-27 07:44:58', max_length=30),
        ),
    ]
