# Generated by Django 2.0.1 on 2018-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CartGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(verbose_name='date collected')),
                ('amp_hours', models.FloatField()),
                ('mileage', models.FloatField()),
                ('hours', models.IntegerField()),
            ],
            options={
                'ordering': ['collection_date'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='data',
            field=models.ManyToManyField(to='carts.DataSet'),
        ),
        migrations.AddField(
            model_name='cart',
            name='group',
            field=models.ManyToManyField(to='carts.CartGroup'),
        ),
    ]
