# Generated by Django 2.0.1 on 2018-01-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartFleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_acquired', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='data',
            new_name='data_set',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='collection_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='cartfleet',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
