# Generated by Django 2.0.1 on 2018-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20180527_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={},
        ),
        migrations.RemoveField(
            model_name='fault',
            name='code',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='data_set',
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='name',
            field=models.CharField(default='2018-05-27 10:49:57', max_length=30),
        ),
    ]
